services:
    prestashop.module.litespeedcache.warmup:
        class: LiteSpeed\Cache\Warmup
        tags:
            - { name: 'console.command' }

    prestashop.module.litespeedcache.guestmode.warmup:
        class: LiteSpeed\Cache\GuestModeWarmup
        tags:
            - { name: 'console.command' }            